name: LifeSteal
version: '4.1.1'
main: org.fliff.lifeSteal.LifeSteal
api-version: '1.21'
authors: [ Fluffy ]
commands:
  resethearts:
    description: Resets the hearts of a player.
    usage: /resethearts <player>
    permission: lifesteal.reset
  withdrawheart:
    description: Withdraws hearts into items.
    usage: /withdrawheart <amount>
    permission: lifesteal.withdraw
  giveheart:
    description: Give secure heart items
    usage: /giveheart <player> <amount>
    permission: lifesteal.giveheart
  lifesteal:
    description: Main LifeSteal command
    usage: /lifesteal <check|reload>
    permission: lifesteal.main